# Generated by Django 2.0.3 on 2018-04-03 18:55

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('text', models.TextField()),
                ('entities', djongo.models.fields.ListField()),
                ('retweet_count', models.IntegerField()),
                ('favorite_count', models.IntegerField()),
                ('geo', djongo.models.fields.ListField()),
                ('country', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('screen_name', models.TextField()),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('utc_offset', models.IntegerField()),
                ('time_zone', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eight2x_app.User'),
        ),
    ]
