# Generated by Django 2.0.2 on 2018-04-24 03:50

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eight2x_app', '0002_auto_20180403_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='labels',
            field=djongo.models.fields.ListField(default=[]),
        ),
        migrations.AddField(
            model_name='status',
            name='predicted_country',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='sentiment',
            field=models.TextField(default=''),
        ),
    ]
