# Generated by Django 2.0.2 on 2018-04-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eight2x_app', '0003_auto_20180424_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='predicted_country',
            field=models.BooleanField(default=False),
        ),
    ]
